<?php
$helper = $this->helper('CognitionHub\Mimir\Helper\Data');
$mimirCompany = $helper->getConfigModule('general/mimir_company');
?>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        fetch('/mimir/session/getSessionId')
        .then(response => response.json())
        .then(data => {
            const company = "<?php echo $mimirCompany ?>"
            window.$mimirCustomerID = data.mimir_customer_id

            mimirScript = document.createElement('script')
            mimirScript.type = "text/javascript"
            mimirScript.src = `https://api.cognitionhub.no/static/${company}.js`
            document.getElementsByTagName('head')[0].appendChild(mimirScript)
        });
       
    });
</script>